name: CI orchestrator

on:
  pull_request:
    branches:
      - main

jobs:
  #
  # License and Markdown Check
  #
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@v12
    secrets:
      pat_token: ${{ secrets.PAT_TOKEN_REPO_WORKFLOW }}

  #
  # Detect changes to start relevant workflows
  #
  changes:
    uses: ./.github/workflows/detect-changes.yml

  ci_dotnet:
    needs: changes
    if: ${{ needs.changes.outputs.dotnet == 'true' }}
    uses: ./.github/workflows/ci-dotnet.yml
    secrets: inherit

  ci_client_package:
    needs: changes
    if: ${{ needs.changes.outputs.client_package == 'true' }}
    uses: ./.github/workflows/publish-marketparticipant-client.yml
    secrets: inherit

  render_c4model_views:
    needs: changes
    if: ${{ needs.changes.outputs.render_c4model_views == 'true' }}
    uses: Energinet-DataHub/.github/.github/workflows/structurizr-render-diagrams.yml@xdast
    with:
      structurizr_workspace_filename: views
      included_model_filename: model
    secrets:
      pat_token_retrigger_workflow: ${{ secrets.pat_token_repo_workflow }}

  #
  # Branch policy status check
  #

  allow_merge_ci_orchestrator:
    runs-on: ubuntu-latest
    needs:
      [ci_base, ci_dotnet, ci_client_package, render_c4model_views]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"

          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
